### ISSUE TITLE
Cookies For Websocket?

### ISSUE THREAD

**Issue by bitnom** [cubiclesoft/ultimate-web-scraper#10]
I have a site running a websocket server I need to scrape that requires login first. I need to pass a cookie for my websocket connection. Possible here?

**Comment by cubiclesoft** [comment]
Yup!  The last parameter of `Connect()` lets you pass in a WebBrowser object.  You should be able to make your web requests to login with a WebBrowser instance and then pass it into `Connect()` for the WebSocket class.
