### ISSUE TITLE
Unable to use proxies with Https urls.

### ISSUE THREAD

**Issue by darkwish121** [cubiclesoft/ultimate-web-scraper#13]
Greetings,

I am trying to load a page via and proxy url. But it is not working with https urls. I am trying as follow.

$options = [
            'proxyurl' => 'http://fsrsif:cCvwgNDs@123.107.198.149:29842'
        ];
        $result = $web->Process("https://www.pedestrian.tv/", $options);

Can you please guide me what is the problem?

**Comment by cubiclesoft** [comment]
Add `"proxyconnect" => true` to your options array.  That will instruct the proxy to pass your traffic through (via CONNECT) instead of proxying the request.  Note that not all proxies support/allow CONNECT - depends on the configuration.

**Comment by darkwish121** [comment]
This is the error occur when I use proxyconnect => true

``    

                        [success] => 
                          [error] => Unable to retrieve content.  A stream_socket_enable_crypto() failure occurred.  Most likely cause:  Tunnel connection failure or incompatible crypto setup.
                           [info] => Array
                            (
            [success] => 
            [error] => A stream_socket_enable_crypto() failure occurred.  Most likely cause:  Tunnel connection failure or incompatible crypto setup.
            [errorcode] => stream_socket_enable_crypto_failed
            [url] => https://whatismyipaddress.com/
            [options] => Array
                (
                    [headers] => Array
                        (
                            [Accept] => text/html, application/xhtml+xml, */*
                            [Accept-Language] => en-us,en;q=0.5
                            [Cache-Control] => max-age=0
                            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
                        )

                    [proxyurl] => http://marif:cCvpgMDf@23.106.192.139:29842
                    [proxyconnect] => 1
                    [streamtimeout] => 300
                )

            [firstreqts] => 1537854320.9626
            [numredirects] => 0
            [redirectts] => 1537854320.9626
            [totalrawsendsize] => 0
        )

    [state] => Array
        (
            [async] => 
            [startts] => 1537854320.9626
            [redirectts] => 1537854320.9626
            [timeout] => 
            [tempoptions] => Array
                (
                    [proxyurl] => http://marif:cCvpgMDf@23.106.192.139:29842
                    [proxyconnect] => 1
                    [streamtimeout] => 300
                    [headers] => Array
                        (
                        )

                )

            [httpopts] => Array
                (
                    [headers] => Array
                        (
                        )

                )

            [numfollow] => 20
            [numredirects] => 0
            [totalrawsendsize] => 0
            [profile] => auto
            [url] => https://whatismyipaddress.com/
            [urlinfo] => Array
                (
                    [scheme] => https
                    [authority] => whatismyipaddress.com
                    [login] => 
                    [loginusername] => 
                    [loginpassword] => 
                    [host] => whatismyipaddress.com
                    [port] => 
                    [path] => /
                    [query] => 
                    [queryvars] => Array
                        (
                        )

                    [fragment] => 
                )

            [state] => initialize
            [httpstate] => 
            [result] => 
            [dothost] => .whatismyipaddress.com
            [cookiepath] => /
            [options] => Array
                (
                    [headers] => Array
                        (
                            [Accept] => text/html, application/xhtml+xml, */*
                            [Accept-Language] => en-us,en;q=0.5
                            [Cache-Control] => max-age=0
                            [User-Agent] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
                        )

                    [proxyurl] => http://marif:cCvpgMDf@23.106.192.139:29842
                    [proxyconnect] => 1
                    [streamtimeout] => 300
                )

        )

    [errorcode] => retrievewebpage

**Comment by cubiclesoft** [comment]
Add `"debug" => true` to your options array.  That will allow `stream_socket_enable_crypto()` to emit whatever errors are being suppressed from the underlying SSL library.  I normally suppress PHP warnings and errors for security reasons.

On the plus side, there is only one place in `http.php` where that message is emitted and it is AFTER a successful CONNECT call.  So it appears that the proxy is allowing the CONNECT to happen to the destination.  However, the SSL/TLS handshake is what is failing now.  Enabling debug mode should hopefully dump out the specific error.  PHP is notorious for obfuscating SSL library errors.

**Comment by darkwish121** [comment]
Thanks for reply, I try this time with debug true not it show me Socket error. I am using HTTP proxy.

                   PHP Warning:  stream_socket_enable_crypto(): supplied resource is not a valid stream resource in /var/www/html/scraper/google_map_search_arif/google_map_search/support/http.php on line 956
                   PHP Stack trace:
                   PHP   1. {main}() /var/www/html/scraper/google_map_search_arif/google_map_search/google_map_search_win.php:0
                   PHP   2. WebBrowser->Process() /var/www/html/scraper/google_map_search_arif/google_map_search/google_map_search_win.php:23
                   PHP   3. WebBrowser->ProcessState() /var/www/html/scraper/google_map_search_arif/google_map_search/support/web_browser.php:426
                   PHP   4. HTTP::RetrieveWebpage() /var/www/html/scraper/google_map_search_arif/google_map_search/support/web_browser.php:181
                   PHP   5. HTTP::ProcessState() /var/www/html/scraper/google_map_search_arif/google_map_search/support/http.php:1794
                  PHP   6. stream_socket_enable_crypto() /var/www/html/scraper/google_map_search_arif/google_map_search/support/http.php:956

**Comment by cubiclesoft** [comment]
I just pushed a fix for this issue (prematurely closing the connection).  Update `http.php` to the latest and try again.

**Comment by darkwish121** [comment]
Thanks for update the http.php. I use that but no luck. Only the warning is slightly change. Is there needs to tunnel through socket? Can I send CURL request via your API? Here is the error I found this time.

                PHP Warning:  stream_socket_enable_crypto(): SSL: Success in /var/www/html/scraper/google_map_search_arif/google_map_search/support/http.php on line 957
                PHP Stack trace:
                PHP   1. {main}() /var/www/html/scraper/google_map_search_arif/google_map_search/google_map_search_win.php:0
                PHP   2. WebBrowser->Process() /var/www/html/scraper/google_map_search_arif/google_map_search/google_map_search_win.php:23
                PHP   3. WebBrowser->ProcessState() /var/www/html/scraper/google_map_search_arif/google_map_search/support/web_browser.php:426
                PHP   4. HTTP::RetrieveWebpage() /var/www/html/scraper/google_map_search_arif/google_map_search/support/web_browser.php:181
                PHP   5. HTTP::ProcessState() /var/www/html/scraper/google_map_search_arif/google_map_search/support/http.php:1796
                PHP   6. stream_socket_enable_crypto() /var/www/html/scraper/google_map_search_arif/google_map_search/support/http.php:957

If I use my old script of CURL then every thing is fine. Here is my function.

                 function getContent($url, $proxy = "") {
                       $curl = curl_init();
                       $headers = array(
                               'Accept-Charset: ISO-8859-1',
                               '<meta http-equiv="Content-Type" content="text/html; '
                              . 'charset=utf-8">'
                       );
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

        if ($proxy != "") {
            curl_setopt($curl, CURLOPT_PROXY, $proxy);
            curl_setopt($curl, CURLOPT_HTTPPROXYTUNNEL, 0);
        }
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($curl, CURLOPT_MAXREDIRS, 10);
        curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 30);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);
        curl_setopt($curl, CURLOPT_COOKIEJAR, realpath('cookie.txt'));
        curl_setopt($curl, CURLOPT_COOKIEFILE, realpath('cookie.txt'));
        curl_setopt($curl, CURLOPT_REFERER, 'http://www.google.com/');
        curl_setopt($curl, CURLOPT_USERAGENT, 
                'Mozilla/5.0 (X11; U; Linux i586; de; rv:5.0) '
                . 'Gecko/20100101 Firefox/5.0');
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE); // ssl certificate
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 2);

        $result ['EXE'] = curl_exec($curl);
        $result ['INF'] = curl_getinfo($curl);
        $result ['ERR'] = curl_error($curl);

        // curl_close($curl);
        unset($url);
        return $result;
    }

**Comment by cubiclesoft** [comment]
Looks like the SSL connection succeeded?  That's the other reason to suppress output from the underlying SSL library:  Weird, random output from PHP that the caller can't do anything about.  Seems like the connection and the request worked.  Ignore the warning and check the result.  It should be working.

On a side note:  Your example cURL code isn't using a CONNECT tunnel.  Okay, so maybe I should have asked what the exact error message is for the non-tunneled version of your code.  I just assumed it was the proxy not passing SSL-oriented traffic onto targets.  If there's an issue there, I'd like to fix that too.  It's been a long time since I used a proxy, so that area of the software's been a little bit ignored.
