### ISSUE TITLE
im trying to download the entire site...css files...js files...images...do you think this library could give good results?

### ISSUE THREAD

**Issue by menriquez** [cubiclesoft/ultimate-web-scraper#18]

**Comment by menriquez** [comment]
so yes...one thing related to this I've run across already...why doesn't the scraper also include the CSS background images and the like from the CSS files when searching for, say, all linked images to the page?

is it possible to scrape the CSS for these images using built-in functions, or do I have to roll my own solution?

**Comment by cubiclesoft** [comment]
The just-released offline downloading example script may be sufficient for your needs as-is:

https://github.com/cubiclesoft/ultimate-web-scraper#offline-downloading

But if it's not what you were expecting, the offline downloader script is pretty modular, so you can grab what you need out of it and/or modify the script for your needs.

Parsing CSS is not really within the scope of this library at this time.  The approach taken for processing CSS files is a bit hacky (i.e. the `ProcessCSS()` function could fail at awkward moments).  Proper CSSFilerStream and CSSFilter classes with full blown state engines similar to the TagFilterStream and TagFilter classes is the more correct solution, but that would require a full dev cycle.

**Comment by Cintrust** [comment]
> Parsing CSS is not really within the scope of this library at this time. The approach taken for processing CSS files is a bit hacky (i.e. the `ProcessCSS()` function could fail at awkward moments). Proper CSSFilerStream and CSSFilter classes with full blown state engines similar to the TagFilterStream and TagFilter classes is the more correct solution, but that would require a full dev cycle.


Where can I get those css filters

**Comment by cubiclesoft** [comment]
As far as I know they don't exist.  At least not in this library.  Obviously web browsers parse CSS but nothing for automation purposes.  Writing a proper parser with a state engine requires reading and understanding the CSS specification and then transforming those Standard(s) into real-world parsers and validation test suites.
