### ISSUE TITLE
Js conflict with internal references 

### ISSUE THREAD

**Issue by Cintrust** [cubiclesoft/ultimate-web-scraper#20]
https://github.com/cubiclesoft/ultimate-web-scraper/blob/75f9c5c7b299d86a5691d681a22f0c6dd6442279/offline_download_example.php#L478

This line causes an issue with 
JS expecially jquery, because instead of having only the fragments as the url eg `#topic or # `, you end up getting `index.html#topic or index.html` as the url, and this ends up breaking the pages that depends on the normal behavior

**Comment by cubiclesoft** [comment]
Fixed.  Thanks for catching this.
