### ISSUE TITLE
offline mode should not process the contents of 404 response

### ISSUE THREAD

**Issue by Cintrust** [cubiclesoft/ultimate-web-scraper#21]
https://github.com/cubiclesoft/ultimate-web-scraper/blob/75f9c5c7b299d86a5691d681a22f0c6dd6442279/offline_download_example.php#L646

there is no need to process the contents of a 404 reponses since we are not storing it.

secondly it is causing issues where by the 404 response contains other links, the library just processes it , and ends up downloading in my case the whole url visible under localhost:// which include phpmyadmin etc. this was beacuse the the 404 response appache displays comes with some links pointing to `http://localhost` etc.

**Comment by cubiclesoft** [comment]
A HTTP 404 response is not a guarantee of no content.  I've seen plenty of examples where a 404 still returns real content even though it is not Standards Conformant to do so.  404 pages from a server may also have additional links worth following.  If the script is downloading content from a localhost server, then that's a security vulnerability on your computer - not the script.  An attacker can potentially XSRF your localhost machine and you should deal with that by turning off directory listing in Apache.

IMO, upstream Apache should disable directory listing by default.  It's a setting that probably shouldn't even exist as it exposes internal file system structures to the browser without requiring any access controls.

This is an example script.  It's meant for people to modify for their use-case.
