### ISSUE TITLE
PHP 7.4 Array and string offset access syntax with curly braces is deprecated.

### ISSUE THREAD

**Issue by shazahm1** [cubiclesoft/ultimate-web-scraper#25]
Title pretty much says it all. Support for curly brace syntax array access is deprecated in PHP 7.4. The library makes extensive use of that syntax. Are there plans to change the syntax?

**Comment by shazahm1** [comment]
Well, darn, I should have pull down the latest master before opening this. Sorry!

**Comment by cubiclesoft** [comment]
This was already fixed globally.  If there's still an issue, please let me know where you are seeing it.
