### ISSUE TITLE
How to find specific div with class name?

### ISSUE THREAD

**Issue by eizil** [cubiclesoft/ultimate-web-scraper#27]
Hi,

i try to use the scraper to find specific div with its content, how can I achieve this?

tried to use

```
Find("div")->Filter("class[class-name]");

Find("div[class]")->Filter("class-name");
```

both didn't really filter out the output.

thanks

**Comment by eizil** [comment]
okay never mind, i found the correct way to write it.

`Find('div[class="class-name"]');`

**Comment by cubiclesoft** [comment]
The correct way is to use CSS style class selectors:

`Find('div.class-name')`

The reason for doing that is because the class attribute can contain multiple classes.  If the above doesn't work, then that would be a bug.

**Comment by eizil** [comment]
> The correct way is to use CSS style class selectors:
> 
> `Find('div.class-name')`
> 
> The reason for doing that is because the class attribute can contain multiple classes. If the above doesn't work, then that would be a bug.

thank you for the clarification.

**Comment by cubiclesoft** [comment]
I do make the assumption that people know how to use at least basic CSS selectors for Find().  For those who already do web development, CSS3-style selectors are an extremely natural and comfortable option.  For everyone else, it might be a bit awkward to get started.

I've added a link to a CSS3 selector cheat sheet that looks fine to me into the first couple of examples in the main repo README.  Here's the link to the Gist:

https://gist.github.com/magicznyleszek/809a69dd05e1d5f12d01

**Comment by eizil** [comment]
> I do make the assumption that people know how to use at least basic CSS selectors for Find(). For those who already do web development, CSS3-style selectors are an extremely natural and comfortable option. For everyone else, it might be a bit awkward to get started.
> 
> I've added a link to a CSS3 selector cheat sheet that looks fine to me into the first couple of examples in the main repo README. Here's the link to the Gist:
> 
> https://gist.github.com/magicznyleszek/809a69dd05e1d5f12d01

it not that I don't know how CSS3 selector works, I just not sure how the FInd work, if I know it use the standard css selector, It would be clear from the beginning. 

Thanks anyway for the explanation 😊 cheers
