### ISSUE TITLE
Composer Package

### ISSUE THREAD

**Issue by 3zzy** [cubiclesoft/ultimate-web-scraper#3]
Possible to make it a composer package for easy installation?

**Comment by cubiclesoft** [comment]
The core CubicleSoft directory structure is not compatible with Composer (and I like it that way).  If you want Composer-like functionality, use this package as a git module instead, which, incidentally, is a more correct way to pull down software from GitHub.  I, nor anyone else, should have to maintain metadata inside the version control system that git already provides.

**Comment by IsaacInsoll** [comment]
Is it possible for you to reconsider this decision now six years later?

**Comment by cubiclesoft** [comment]
https://github.com/cubiclesoft/php-libs-to-composer
