### ISSUE TITLE
Support for "*" CSS selector

### ISSUE THREAD

**Issue by nindzia3** [cubiclesoft/ultimate-web-scraper#30]
Coming from PHP Simple HTML Parser, which doesn't support pseudo-selectors yet, but supports the `*`, I was happy to finally find a parser (tag_filter) that does that. But now it lacks support for the `*` selector, which is really dissapointing. Otherwise it works great and finds any other selector fine.

**Comment by nindzia3** [comment]
Sorry, I actually found something in documentation [using the `*` selector](https://github.com/cubiclesoft/ultimate-web-scraper/blob/master/docs/tag_filter.md#tagfilternodetype), but I don't know why it doesn't work in my situation.

```php
$styles = [
	'*',
	'table',
	'td',
	'a',
	'img',
	'.button',
	'.logo',
	'h1',
	'p',
	'p:last-child',
	'hr',
	'.body',
	'.text'
];

include 'tag_filter.php';

$htmloptions = TagFilter::GetHTMLOptions();

$html = TagFilter::Explode($document, $htmloptions); // $document is a function parameter

$root = $html->Get();

foreach ($styles as $selector) {
	foreach ($root->Find($selector) as $element) {
		echo '<pre>' . print_r($element, true) . '</pre>';
	}
}
```
`Find()` finds and outputs every DOM element from the array, except nothing of the "*" elements.

**Comment by nindzia3** [comment]
Debugged a little and found out that the selector might be invalidated here.
https://github.com/cubiclesoft/ultimate-web-scraper/blob/79c1512b034e7187ce956ad43f8e0ebc3717e2ad/support/tag_filter.php#L3136

**Comment by cubiclesoft** [comment]
Confirmed.  I just pushed a fix that seems to work.  The wildcard was correctly handled by the CSS3 selector parser but was NOT being handled by the backtracking logic for element handling.
