### ISSUE TITLE
do not remove spaces in links

### ISSUE THREAD

**Issue by KoljaL** [cubiclesoft/ultimate-web-scraper#31]
the origin href was: `domain.de/some folder with spaces/image.jpg`

after scraping it is:  `domain.de/somefolderwithspaces/image.jpg`

**Comment by cubiclesoft** [comment]
Should be fixed now.  Now encoding spaces rather than removing.  Still removing nulls, carriage returns, newlines, and tabs.

That's technically an invalid URL.  No server will accept it without first modifying the URL.  Browsers make lots of concessions for broken HTML.
