### ISSUE TITLE
time fetching from site

### ISSUE THREAD

**Issue by Romi-KS** [cubiclesoft/ultimate-web-scraper#34]
there at the site it is 7:30 pm. But I am scrapping and getting 2 Pm. I suppose its autoconverting into GMT of something. Please advice

**Comment by cubiclesoft** [comment]
Please clarify what you are referring to.  If you are referring to the "Date" and "Last-Modified" HTTP headers returned by a web server, then that is part of the HTTP specification.

**Comment by cubiclesoft** [comment]
Closing due to non-response.  If someone supplies the requested info, this issue can be reopened.
