### ISSUE TITLE
Error when trying to load a saved WebBrowser state

### ISSUE THREAD

**Issue by mbouksim** [cubiclesoft/ultimate-web-scraper#36]
Hi,
I'm trying to save the state of a WebBrowser instance to be used in another  script. I used the same exemple in the documentation

**Script A:**
`file_put_contents("webState.json", json_encode($web->GetState()));`

**Script B:**
`$prevstate = json_decode(file_get_contents("webState.json"));
$web = new WebBrowser($prevstate);`

I got the state saved correctly but I keep getting the following errors when trying to use the saved state in the script B (and the state is not loaded the to WebBrowser instance)

`
Warning: array_merge(): Expected parameter 2 to be an array, object given in C:\wamp64\www\scrap\support\web_browser.php on line 38

Notice: Undefined index: maxfollow in C:\wamp64\www\scrap\support\web_browser.php on line 400

Notice: Undefined index: referer in C:\wamp64\www\scrap\support\web_browser.php on line 409`

Thank you :)

**Comment by cubiclesoft** [comment]
Fixed the problem with the documentation.  `json_decode()` needs the second parameter to be `true` to decode the object as a standard PHP array.  I wrote the documentation examples without testing all of them.  `GetState()` and `SetState()` have caveats in that old/stale session information can end up being preserved in a broken state on disk and your code should not make the assumption that your session is preserved indefinitely on the server side of things (e.g. rebooting the server might flush active sessions).  That's not really the fault of the library but just something to be aware of.
