### ISSUE TITLE
Scrap html list

### ISSUE THREAD

**Issue by caifan125** [cubiclesoft/ultimate-web-scraper#39]
Hi, I am working with a select list and I would like to select one of the options I have, do you have an example for working with that?
My other question is, in the same select, when I change the option, the page change the information based in the option I selected,  but this is working with javascript and for what I read, this is the only limitation of this library but it is possible, what is your recommendation for working with this?

Best

**Comment by cubiclesoft** [comment]
It depends entirely on how the page is handling the changes to the select box.  You can, generally speaking, mirror anything the web browser does on the network.  What I mean by not working with Javascript is that it won't execute Javascript.

The Developer Console (press F12 in most web browsers) is typically how you figure out what components of a webpage you are interested in extracting.  The WebBrowser class can extract standard HTML form elements and make it easy to automate forms but forms and elements that are generated using pure Javascript won't be picked up.  The Network tab of the Developer Console is your friend here.  Just watch what is sent to and returned by the web server and mirror that in your own requests.

Feel free to drop in on Discord if you need further assistance/help/guidance.

Closing as not an issue.
