### ISSUE TITLE
How to post images using html form handling?

### ISSUE THREAD

**Issue by farazirfan47** [cubiclesoft/ultimate-web-scraper#5]
How to use form for uploading image ? 

$form = $result["forms"][0];
$form->SetFormValue("q", "barebones cms");
$result2 = $form->GenerateFormRequest("btnK");
 $result = $web->Process($result2["url"], "auto", $result2["options"]);

**Comment by cubiclesoft** [comment]
Updated the documentation with the new section entitled "Uploading Files".

You can do something like this:

```php
$form->SetFormValue("photo", array("filename" => "mycat.jpg", "type" => "image/jpeg", "data" => file_get_contents("/path/to/mycat.jpg")));
```
