### ISSUE TITLE
Unable to establish a connection to 'tls://dealer.one2car.com:443'.

### ISSUE THREAD

**Issue by farazirfan47** [cubiclesoft/ultimate-web-scraper#6]
I made a scraper that works perfectly on locahost but when It deployed to server give this error. any Idea where is the problem ? Thanks

**Comment by cubiclesoft** [comment]
GitHub is not the appropriate venue to ask support questions.  I don't know the exact answer to the question - SSL/TLS issues are generally hard to diagnose.  See the documentation section Debugging SSL/TLS.

**Comment by farazirfan47** [comment]
No problem! I found the solution. Thanks
