### ISSUE TITLE
How do I simulate a click event on an anchor tag?

### ISSUE THREAD

**Issue by ThreeHDM** [cubiclesoft/ultimate-web-scraper#8]
I submit a form and obtain a list of itenms that only shows ten elements per page. How do I "click" the "next page" anchor tag or the "page number" in order to crawl all the results?

**Comment by cubiclesoft** [comment]
This is an excellent question.  And one better addressed by updating the documentation as it is a common enough scenario when scraping data.

Documentation updated:  See the section on "Handling Pagination".

**Comment by ThreeHDM** [comment]
Thanks I will look into it!
